---
- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Add/Remove Group"
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mygroups }}"
  when: item.gid is defined

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Add/Remove Group with auto gid"
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mygroups }}"
  when: item.gid is not defined
